name: Run Container Scan for SuperMario Image

on:
  push:
    branches:
      - master

env:
  VERSION: latest   # you can also use ${{ github.sha }} if you want per-commit tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t docker.io/sreerajmurali/supermariogitopsproject:${{ env.VERSION }} .

      - name: Push Docker image
        run: |
          docker push docker.io/sreerajmurali/supermariogitopsproject:${{ env.VERSION }}

      - name: Debug VERSION
        run: echo "VERSION=${{ env.VERSION }}"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
           scan-type: image
           image-ref: docker.io/sreerajmurali/supermariogitopsproject:${{ env.VERSION }}
           exit-code: '1'
           severity: 'CRITICAL,HIGH'