name: "Run Container Scan on Super Mario Docker Image with Quality Gate"

on:
  push:
    branches:
      - master

jobs:
  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Calculate Version
        id: version
        run: |
          VERSION=$(cat version.txt)
          NEW_VERSION=$((VERSION + 1))
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Get Docker Image from Docker Hub
        run: |
          docker pull docker.io/${{ secrets.DOCKERHUB_USERNAME }}/supermariogitopsproject:${{ env.VERSION }}
          docker save -o supermariolatestdockerimage.tar docker.io/${{ secrets.DOCKERHUB_USERNAME }}/supermariogitopsproject:${{ env.VERSION }}

      # - name: Run Trivy vulnerability scanner in tarball mode
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     input: /github/workspace/supermariolatestdockerimage.tar
      #     exit-code: '1'
      #     severity: 'CRITICAL,HIGH'
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/supermariogitopsproject:${{ env.VERSION }}
          exit-code: '1'  # let Trivy return non-zero for real findings
          severity: 'CRITICAL,HIGH'

